# Generated by Django 3.2 on 2022-08-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220814_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_postcode',
            new_name='default_post_code',
        ),
    ]
