# Generated by Django 4.1 on 2022-08-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
