# Generated by Django 3.2 on 2022-08-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coutry',
            new_name='country',
        ),
    ]
