# Generated by Django 3.2 on 2022-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_coutry_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
