# Generated by Django 3.2 on 2022-07-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220717_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ranting',
            new_name='rating',
        ),
    ]
