# Generated by Django 3.2 on 2022-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220718_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_list',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.BooleanField(blank=True),
        ),
    ]
