# Generated by Django 3.2 on 2022-08-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220718_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
