# Generated by Django 3.2 on 2022-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220816_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='set_product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='set_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
