# Generated by Django 3.2 on 2022-08-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220816_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='set_product_id',
        ),
    ]
