# Generated by Django 3.2 on 2022-08-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_set_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='fastening',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='heels_mesurement',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='lining_material',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='sole',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='technology',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='upper_material',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='stock',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
