# Generated by Django 3.2 on 2022-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220816_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='fastening',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='heels_mesurement',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='lining_material',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='sole',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='technology',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='upper_material',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
